name: puzzlin_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  # flutter_svg: ^2.0.10+1 # <--- ELIMINA O COMENTA ESTA LÍNEA

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/ # Ruta general para imágenes (PNG, JPG, etc.)
    - assets/images/icons/ # Ruta específica donde está tu logo (PNG, JPG)
    - assets/images/puzzles/ # Para las imágenes de los puzzles
    - assets/audio/ # Para los archivos de audio

  # ... (el resto del archivo, como la sección de fuentes, permanece igual)